parallella/pal

README.md
Doing this as a pull to check whether travis will kick in.
=> README: Spelling fixes

src/math/p_abs.c, src/math/p_exp.c, src/math/p_sincos.c
=> math: p_abs, p_exp: Remove `const` args from impl.

src/math/p_dot.c, src/math/p_max.c, src/math/p_mean.c, src/math/p_median.c, src/math/p_min.c, src/math/p_mode.c, src/math/p_sum.c, src/math/p_sumsq.c
Since scalar is one-dimensional, it can't be iterated.
Fix also incorporates impl. file documentation changes.
=> math: Fix logic of functions with scalar output

src/image/p_gauss3x3.c
=> image: p_gauss3x3: Add function implementation

src/image/p_box3x3.c, src/image/p_gauss3x3.c, src/image/p_prewitt3x3.c, src/image/p_sobel3x3.c
Constant values replaced by their reciprocals.
=> image: Replace division with multiplication

src/image/p_conv2d.c
A rather naive implementation.
Written with the assumption of odd sized kernel.
Using p_sum, p_inv and p_dot from math module API.
=> image: p_conv2d: Add function implementation

src/math/p_max.c, src/math/p_min.c
Removes the need of constant values for comparison.
(Sometimes the most obvious solution comes just on the next day)
=> math: p_max, p_min: Remove magic values

src/math/p_dot.c, src/math/p_mean.c, src/math/p_sum.c, src/math/p_sumsq.c
Minor memory optimization perks:
reducing global memory writes at a cost of temporary variable.
Resolves #30.
=> math: Optimize global memory writes of scalar output functions

src/image/p_median3x3.c
Targeting memory traffic efficiency.
=> image: p_median3x3: Add function implementation

examples/base/Makefile.am, examples/base/median_task.c, src/math/p_median.c
Issue reference: #54
Signed-off-by: Ian Griffiths <6thimage@gmail.com>
=> Add p_median to math library (with simple example)

src/dsp/p_conv.c
Please notice the changes in the comments as well as the method signature; a convolution is supposed to have an output length equal to the sum of the lengths of the input vectors, minus one.
=> Implemented method

src/math/p_median.c
Issue reference: #54
Pull request reference: #56
Signed-off-by: Ian Griffiths <6thimage@gmail.com>
=> Removed divisions in p_median

include/pal_math.h, src/math/p_cos.c, src/math/p_sin.c
=> added M_FLOOR and M_NORMALIZE_RADIANS macros. added basic sin and cos funcs

tests/math/Makefile.am
=> tests: math: Mark all scalar output functions

src/math/p_ftoi.c
Do we need to throw errors?
assert(x >= LONG_MIN-0.5);
assert(x <= LONG_MAX+0.5);
=> Author p_ftoi.c

configure.ac, examples/Makefile.am, examples/image/Makefile.am, examples/image/harris.c, include/pal_image.h, src/image/Makefile.am, src/image/p_harris3x3.c
The Harris corner detection response filter
(raw filter without threshold and non-maxima suppression)
With example.
Signed-off-by: Anaël Seghezzi <anael@maratis3d.com>
=> Image: Harris response filter

src/image/p_gauss3x3.c
- cols and rows were reversed
- removed some additions
=> Image: gaussian - bug correction + speed

src/math/p_itof.c
To be fair, the old code was faster, but it didn't do anything. :)
=> Someone forgot to write code for p_itof()

src/math/p_itof.c
Google style guide http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Local_Variables
"Place a function's variables in the narrowest scope possible, and initialize variables in the declaration."
Signed-off-by: Tom Anderson <github@tom-anderson.com>
=> Initialize variable in the declaration

src/math/p_absdiff.c
I had a pull request up for this already but it was messy - sorry, I'm new to branching... >.<
abs() changed recently so this is to make absdiff() look similar in definition
=> make absdiff() reflect recent changes to abs()

README.md
Developer Certificate of Origin
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA
Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under …
=> Fixed typo (your are ready -> you are ready)

src/math/p_a_inv.c, src/math/p_abs.c, src/math/p_inv.c, src/math/p_invsqrt.c, src/math/p_itof.c, src/math/p_popcount.c, src/math/p_sin.c, src/math/p_sort.c, src/math/p_sqrt.c
=> math: Cleanup unused included libraries

src/math/p_ftoi.c
Float to int is performed by truncating towards zero to the nearest integer.
Remove a note that I had added earlier as well as an inconsistent punctuation.
=> Update description with conversion method

QUESTIONS.md
Improve document for better markdown rendering, more readability.
=> doc: Update QUESTIONS.md

src/image/p_scharr3x3.c, src/math/p_invcbrt.c
Changed division operator to approximation, borrowed from p_inv.c.
Also, an idea: maybe it would be okay to add library function for calculating inverse value of single number? That way it could be used everywhere instead of division to reduce code size (unless calling additional function is bigger evil than code repeated in multiple places).
=> math: p_invcbrt: change division to approximation

include/pal_image.h, src/image/p_sad16x16.c, src/image/p_sad8x8.c
image:
p_sad16x16.c
p_sad8x8.c
=> Sum of absolute differences(sad)

include/pal_image.h, src/image/p_sad16x16.c, src/image/p_sad8x8.c
replace fabs with bit operation in sad* functions
=> fabs to bit operation

src/dsp/p_conv.c
Removed the extra variable mentioned in https://github.com/parallella/pal/pull/180
I found the other improvement unnecessary as explained in that pull request
=> dsp/conv:  Minor imporvement 

src/math/p_exp.c
This implements the natural exponential function using a polynomial approximation with an error less than 3e-5.
=> math:exp: Implement the natural exponential function

src/image/p_box3x3.c, tests/image/Makefile.am, tests/image/check_p_box3x3_f32.c
Signed-off-by: Paul Sokolovsky <pfalcon@users.sourceforge.net>
=> Optimize p_box3x3_f32().

src/math/p_tan.c
This is an implementation of the tangent function as a polynomial approximation with error less than 2e-8.
I left the existing unit testing data file alone.
=> math:tan: Implement the tangent function

src/math/Makefile.am, src/math/p_asin.c, src/math/p_sqrt.c, src/math/p_sqrt.h
This implements the inverse sine function using a polynomial approximation with error less than 5e-5.
Note that the formula uses a square root, so I moved the core square root algorithm into a header file, so I could use it inline.
=> math:asin: Implement the inverse sine function

src/math/p_atan.c
This implements the inverse tangent function using a polynomial approximation with error less than 1e-5.
=> math:atan: Implement the inverse tangent function.

README.md
Signed-off-by: Andreas Olofsson <andreas@adapteva.com>
=> Removing redundant benchmark table

src/base/devices/posix/epiphany/device.c, src/base/devices/posix/epiphany/loader.c
Updated support for epiphany device
Signed-off-by: Peter Saunderson <peteasa@gmail.com>
=> Device epiphany
