parallella/pal

src/image/p_conv2d.c

Both function name and its arguments' order were differing.
Refers to image/p_conv2d
> another issue reference #6

#6 - Fix inconsistency between header/implementation

---

src/math/p_popcount.c

Using classic sideways addition method.
It counts all bits in just 12 operations for 32 bit integer.
This commit resolves #28.

math: p_popcount: Implement function logic

---

src/math/p_sincos.c

Naive implementation using already defined API functions.
Removed math.h include since used funcs reside in pal_math.h
included with pal.h
Resolves #32.

math: p_sincos: Add function implementation

---

src/math/p_popcount.c

An adaptation of p_popcount_u32 methodology, with:
- masks of 64 bit length
- final shift factor changed from 24 (32-8) to 56 (64-8)
Resolves #33.

math: p_popcount_u64: Add function implementation

---

src/image/p_sad16x16.c
src/image/p_sad8x8.c

Eg. running p_sad8x8 on image of size 8x10 will produce a result vector of size 3.

doc: p_sad: Change result type from scalar to vector

---

src/math/p_sqrt.c

This is based on the inverse function described here http://en.wikipedia.org/wiki/Fast_inverse_square_root
Tests pass on x86_64 with two newton passes, but this is highly specific to IEEE 754 binary format.

added p_sqrt_f32 using magic constant

---

src/math/p_abs.c

IEEE 754 floats most significant bit is the sign bit.  Because bitwise operators aren't allowed on floating point values, cast to 32 bit int, clear the sign bit, and assign to the destination vector.

Branchless absolute value toggling sign bit

---

examples/base/Makefile.am
examples/base/mode_task.c
src/math/p_mode.c

In order to test this code I implemented very basic versions of p_sort, p_memcpy and p_malloc using the C standard library. I can pull them as well if needed.
Closes: parallella/pal#51
Is part of: parallella/pal#41
Signed-off-by: Wesley Ceraso Prudencio <wesleyceraso@gmail.com>

math: p_mode: Add p_mode function implementation and example

---

src/image/p_sobel3x3.c

Parallella benchmarked at >225 MPixels/second across 16 cores. Code compiled to about ~890 Bytes.  The previous code was buggy and 2000x slower because it used the math library sqrt function.  This code uses a fast approximation to the square root within the hypotenuse routine, using two Newton iterations for higher precision.  The second iteration can be removed to increase performance and decrease code size, but sacrifices some precision.  The first unrolled code block may be removed (commented within code) in order to reduce code size, but this sacrifices performance.  The routine 'my_hypot' is inlined within the sobel routine for performance.  Code uses the builtin_fmaf to strongly suggest to the compiler to generate fmadd instructions.

Achieves ~60% peak with fast approx to hypotenuse

---

src/image/p_harris3x3.c

Implements an alternative to classical harris response without division.
Original formula can be enabled at compile time by defining
"PAL_HARRIS_HIQ"
Signed-off-by: Anaël Seghezzi anael@maratis3d.com

Image: Harris response no division

---

include/pal_math.h

A fragment of the warnings I get:
```
In file included from ../../include/pal.h:4:0,
from mode_task.c:1:
../../include/pal_math.h:10:0: warning: "M_E" redefined
#define M_E 2.71828182845904523540        /* e */
^
In file included from ../../include/pal_math.h:3:0,
from ../../include/pal.h:4,
from mode_task.c:1:
/usr/include/math.h:367:0: note: this is the location of the previous definition
^
In file included from ../../include/pal.h:4:0,
from mode_task.c:1:
../../include/pal_math.h:11:0: warning: "M_LOG2E" redefined
#define M_LOG2E 1.44269504088896340740    /* log 2e */
^
In file included from ../../include/pal_math.h:3:0,
from ../../include/pal.h:4,
from mode_task.c:1:
/usr/include/math.h:368:0: note: this is the location of the previous definition
^
```

pal_math.h: Fix warnings about redefined constants

---

src/math/p_ftoi.c

Get the sign bit from the input float and set that sign bit on 0.5f rounding value so we can always add the rounding value to the input instead of checking the sign and branching to add or subtract 0.5f.  Used #define for the magic number to help be more self documenting.  Don't know if that fits the style or not, easy to take it out.

 Branchless version of function

---

include/pal_math.h
src/math/p_median.c

Closes: parallella/pal#57
Is part of: parallella/pal#41
Although there were no implementation of p_median when I started coding, the current is O(n log n) because it sorts the whole array, and uses the stack instead of the heap (stack generally has little space available). My solution have a expected time of O(n) (uses QuickSelect) and uses heap.
Signed-off-by: Wesley Ceraso Prudencio <wesleyceraso@gmail.com>

math: p_median: Improves p_median function implementation and example

---

include/pal_math.h

Based on MacOS SDK shipped with clang on MacOS
Signed-off-by: Gabor Buella <gbuella@gmail.com>

pal_math.h: Fix warnings about redefined constants, clang-on-Mac

---

benchmark/example.c
benchmark/runner.c
benchmark/wrapper.h

Simple, portable code
- only ISO C so far, but time keeping, cycle counting
is going need platform specific things
- this way of measuring is not as accurate as instrumentation,
but more portable, thus gives a better cross-platform picture
The output can be fairly simple, parser friendly
Easy to repeat measurements, with the same, or different input sizes
Scalability can be tested using increasing input sizes
- and fancy plots can be created from the outputs
Results easy to compare between commits, given the same platforms for
running the benchmarks
( Does not check code size )
( Not yet integrated with the autoconfig framework, btw I also vote for cmake )
Signed-off-by: Gabor Buella <gbuella@gmail.com>

Add prototype for performance measuring

---

.gitignore

```
Developer Certificate of Origin
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA
Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, …
```

Fix gitignore to include new Autotools details

---

src/math/Makefile.am

Problem:
File p_stddev.c is not present in Makefile.am
Solution:
Adding file to sources in Makefile.am

math:p_stddev Add function to Makefile.am

---

.gitignore

`git status` gives a massive list of files after a clean checkout and make, this mod reduces that to about half a dozen that may need to be ignored by name.

Ignore update

---

README.md
include/pal_image.h
src/dsp/p_conv.c
src/image/p_conv2d.c
src/image/p_median3x3.c

dsp/p_conv_f32: Remove an extra element in the result, Fix a problem in involving uninitialize memory addresses in computation.                                  
image/p_conv2d_f32: Returns incorrect values as it doesn't flip the kernel in vertical and horizontal directions, Support for rectangular kernels.    
image/p_median3x3.c: For 3x3 median filter, I replaced it with hardwired median search described here: http:users.utcluj.ro/~baruch/resources/Image/xl23_16.pdf
README.md: Typo
Counter example for p_conv_f32
Response from FreeMat:
```
--> x = [1, 2, 3, 4];
--> h = [5,6,7];
--> r = conv(x, h)
r =
5 16 34 52 45 28 
```
Response from pal: 
100.000000, 105.000000, 116.000000, 134.000000, 152.000000, 145.000000, 128.000000, 100.000000
```
float x[4] = {1,2,3,4};
float h[3] = {5,6,7} ; …
```

Fix :  image/conv2  &  dsp/conv,   p_median3x3_f32 : hardwired network 

---

src/dsp/p_fir.c

This is a fix to issue #151. It maintains the idea of evaluating 8 samples simultaneously to leverage vectorization (can get almost 4 times faster on my PC using -O3). I also removed the reference to dbuf from the function description as it does not exist anymore (it was removed from the API in commit #1fa28ced55ebddb522cd383ce41bf0a792aff1). A few details that are worth noticing:
- I used malloc to dynamically allocate the delay line as `p_malloc` is not yet implemented. It should, however, be a simple drop replacement as soon as that function is available.
- The function behaves exactly like MATLAB's `filter`, i.e., the delay line is initialized with 0s (the first nh samples are not operating on a "filled buffer").
- As in MATLAB's `filter`, the filter coefficients are assumed to be in …

dsp: p_fir: Fix FIR filter implementation

---

src/dsp/p_firsym.c

This implementation refers to issue #158. Implementation-wise, it follows the same ideas as `p_fir` (see PR #152 for details). Notes:
* As it is, `p_firsym` implements symmetric FIR filters of odd length (a.k.a., type I). In other words, filters such as `1, 2, 3, 4, 5, 4, 3, 2, 1`. In this case, one would pass `h = {1, 2, 3, 4, 5}` and `nh = 5` to the function.
* There is a longer discussion on the filter type issue on #158, but it all boils down to this: filters that have even length (type 2, e.g., `1 2 3 4 4 3 2 1`) cannot be high pass or band stop. Type I filters have no restrictions.
* `p_firsym` is generally faster than `p_fir`. On ARM cores, it is always faster. On Intel i7, it is only slightly slower for shorter filters (small `nh`). The result of a larger benchmark can be found in …

dsp: p_firsym: Implement p_firsym

---

benchmark/benchmark.c
configure.ac

Hi,
I would like to build PAL on OS X, but OS X doesn't provide the `clock_gettime` function.
I had to make a couple changes in the file `benchmark.c`. I first switched the `platform_clock_t` structure to the type `uint64_t` which is more portable since the `timespec` structure is an extension to the C standard. Then I added a `platform_clock` function for OS X which does the same thing as the one which uses `clock_gettime`.
Now everything builds fine on OS X.

Build on OS X

---

src/dsp/p_firdec.c

I didn't understand what is mean by "This function retains the address of the delay filter memory containing the previous delayed values to allow consecutive processing of blocks."

Implemented decimating FIR filter

---

examples/image/filters.c
src/image/p_gauss3x3.c
src/image/p_prewitt3x3.c
src/image/p_scharr3x3.c
src/image/p_sobel3x3.c

These four operators (Sobel, Prewitt, Scharr, and Gaussian) achieve very high efficiency (63-76% theoretical peak performance with an Epiphany roofline model).  This was achieved using a combination of algorithm improvements for higher throughput and code optimization for higher performance.  The Gauss operator exceeds the 1 Gigapixel/second milestone while the others are all 300+ Megapixels on the Parallella.  The original Gauss constants were incorrect as were the Scharr constants.  The code should be compiled with -O3.

Optimized Sobel, Prewitt, Scharr, and Gaussian local operators

---

src/math/p_atan.c
src/math/p_tan.c

__p_tan_pi_4 (the underlying function of p_tan) now uses 7
multiplications instead of 22. _p_atan now uses 6 instead of 25.
The number of additions for both functions remains the same.
Additionally, an extra float variable has been added to _p_atan,
which holds the square of x.
Signed-off-by: Ian Griffiths <6thimage@gmail.com>

math: p_tan/p_atan: Optimised the number of multiplications.

---

src/image/p_median3x3.c

The included routine is stand-alone (does not depend on external routines).
The biggest hit to performance in the previous code was the use of the memcpy
system call, which has been removed.
A clever reduction in the number of sorting comparisons and swaps was made as
well as a clever comparison with integers, reducing instruction overhead. The
overall performance is closer in line with the other image stencil routines
now.  The total program size was also reduced by approximately 1824 bytes when
calling this routine compared to the previous code. Performance benchmarked
around 105 MegaPixels/second which I feel is pretty good considering the all
the sorting and logical operations that don't require much math.
Signed-off-by: James Ross <james.a.ross@gmail.com>

image: p_median3x3: new sort algrthm,~185x speedup

---

src/image/p_median3x3.c
src/math/p_cbrt.c
src/math/p_invcbrt.c

This patch is related to the poor compilation of the floating point comparison
operation.  The appropriate compiler flags (-mno-soft-cmpsf) must be enabled to
get the compiler to generate efficient code
Only minor formatting to the macros has been made and the code is logically
identical to the previous version.
Signed-off-by: James Ross <james.a.ross@gmail.com>

image:p_median3x3:removed subtract/integer compare

---

src/math/p_sum.c
src/math/p_sumsq.c

Change loop condition and pointer advancing for reduction of asm output (Epiphany) resulting in better performance.
compiled with the default `-O2 -ffast-math -mfp-mode=round-nearest
-ffp-contract=fast` on [gcc.parallella.org](http://gcc.parallella.org/)

math: p_sum, p_sumsq: Improve loop performance
